### ISSUE TITLE
XOR 

### ISSUE THREAD

**Issue by sec13b** [wizardy0ga/XorNtRunner#1]
Encrypt your shellcode using the XOR algorithm.

can you say what you use for XOR shellcode .
thank you

**Comment by wizardy0ga** [comment]
To generate shellcode for testing things, typically i use [msfvenom](https://www.offsec.com/metasploit-unleashed/msfvenom/).

If encryption is what you're after, i have a [tool i released](https://github.com/wizardy0ga/Shell-Crypt) to assist with encrypting shellcode using [XOR](https://en.wikipedia.org/wiki/XOR_swap_algorithm) however some modification to XorNtRunner's code would be required due to the extra features provided by the tool. 

If you're simply looking to encrypt your shellcode using XOR, there's numerous tools available such as [Supernova].

XOR is relatively easy to implement in other languages as well. You could write your own shellcode encrypter if you have previous programming experience :)

**Comment by sec13b** [comment]
the msfvenom command please . no offense.
i use a python script to  encrypt shellcode in XOR, but is detected instant .
